version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached
      - vscode-extension:/root/.vscode-server-insiders

    command: sleep infinity

volumes:
  vscode-extension:
