version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached
      - vscode-extension:/root/.vscode-server-insiders
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket

    command: sleep infinity

volumes:
  vscode-extension:
